### ISSUE TITLE
Can't get rust to work

### ISSUE THREAD

**Issue by trolando** [SSoelvsten/bdd-benchmark#108]
Using EndeavourOS, based on Arch. Installed rust, used `rustup default stable` then `cargo install --force cbindgen` and I get this error:

```
-- Rust Toolchain: 
CMake Error at build/_deps/corrosion-src/cmake/FindRust.cmake:23 (message):
  Could not find toolchain ''

  Available toolchains:

    `stable-x86_64-unknown-linux-gnu`

Call Stack (most recent call first):
  build/_deps/corrosion-src/cmake/FindRust.cmake:449 (_findrust_failed)
  build/_deps/corrosion-src/cmake/Corrosion.cmake:63 (find_package)
  build/_deps/corrosion-src/CMakeLists.txt:73 (include)
```

**Comment by SSoelvsten** [comment]
@nhusung , is this something to fix in your FFI or should I forward this onto Corrosion?

**Comment by nhusung** [comment]
I tried to reproduce this issue in an [ArchLinux Podman container](https://hub.docker.com/_/archlinux) but everything worked fine. Here are the commands I executed inside the container:

```sh
pacman -Syu git gcc cmake make automake autoconf rustup boost hwloc snappy bison flex
rustup default stable
export PATH="$HOME/.cargo/bin:$PATH"
cargo install cbindgen --force
git clone https://github.com/SSoelvsten/bdd-benchmark.git
cd bdd-benchmark
git submodule update --init --recursive
make build
```

@trolando could you please add details on your `$PATH` variable (`echo $PATH` and `which cbindgen`) and the way you installed `rustup` (via Pacman or as described on https://www.rust-lang.org/learn/get-started)? Which Rust version is installed on your system?

**Comment by trolando** [comment]
I had to update the `PATH` variable indeed. While this is mentioned in the README, it could have been more explicit.
