### ISSUE TITLE
Make gathering of statistics optional

### ISSUE THREAD

**Issue by ssoelvsten** [SSoelvsten/bdd-benchmark#34]
Statistics, such as the maximum BDD size should be possible to turn off.

- [ ] Add to CMake a variable (default `OFF`) whether to have statistics in the benchmarks or not. If yes, then also turn on statistics in each BDD package.
- [ ] Add a preprocessor flag if the variable is set to `ON`.
- [ ] Guard running the statistics behind the preprocessor flag.

The only statistics that **always** should be gathered is time.

**Comment by AnnaBlume99** [comment]
This is a misunderstanding, not an actual problem.
